### ISSUE TITLE
Align passwords for Camunda and keycloack

### ISSUE THREAD

**Issue by hisImminence** [camunda/camunda-platform#1085]
At the moment the user/ password for keyclock is `admin`, while for Camunda apps its `demo`. Can this be aligned? 

Question was reported by @HanselIdes:
https://github.com/camunda/camunda-platform/pull/1084#discussion_r1886531203

**Comment by aabouzaid** [comment]
I'd keep it as it doesn't add much value to change it also:
- The change could be confusing for users who are used to it.
- The change could be confusing as it might not be clear which user is which.
- The users can make the change by setting the name in the values file (we just will not adopt it as a default value).
