### ISSUE TITLE
Keycloak redirection issues when using an IP address instead of localhost

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-platform#111]
Hi, we have a prospect who is using the docker compose to setup Camunda platform on a dev server. 

They were not able to authenticate any application (task list, operate, identity,..) since the redirection back from key cloak would always happen on localhost, despite setting the Ipaddress based URL for the identity application. 

The issue was resolved, after the IDENTITY_URL was set in the docker file. We now understand that by default, the IDENTITY_URL property takes localhost and hence the issue. 

Solution : Explicitly set this property also in the docker compose file, so that developers would replace this property as well, and be able to use the docker compose for an environment that is not based on localhost.

**Comment by jessesimpson36** [comment]
I merged  a PR that makes the host configurable via changing the HOST variable in `.env`.  Re-open this ticket if you still have a problem.
