### ISSUE TITLE
Improvement: add version: '3' to docker files 

### ISSUE THREAD

**Issue by dags** [camunda/camunda-platform#12]
Well, said in title. For some people current docker file will fail with 
**_ERROR: Invalid interpolation format for "zeebe" option in service "services": 
 camunda/zeebe:${CAMUNDA_PLATFORM_VERSION:-8.0.0}"_**
if there is no version info on files.

**Comment by menski** [comment]
Hey @dags, which version of docker compose are you using? As far as I know is docker-compose version 3 a legacy version and it's not needed anymore in the latest docker-compose specification to specify a version, see docs 
https://docs.docker.com/compose/compose-file/#version-top-level-element

**Comment by dags** [comment]
do(base) dgil@dgil1:~$ docker -v
Docker version 20.10.14, build a224086

**Comment by menski** [comment]
Thanks for sharing, your docker version is up to date but your compose version is 3 1/2 years old. I guess that's the issue why it cannot handle the newer file format. Would you mind to update your docker-compose version?

**Comment by menski** [comment]
Based on the [compose documentation](https://docs.docker.com/compose/compose-file/compose-versioning/) the latest file format was introduced  with compose 1.27.0

> The latest Compose file format is defined by the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md) and is implemented by Docker Compose 1.27.0+.

The [latest compose](https://github.com/docker/compose/releases) version is 2.4.1 as of this writing.

**Comment by menski** [comment]
I added a note to the README about the file format and the recommended version. I will close this issue for now, let me know if you disagree.
