### ISSUE TITLE
Tasklist REST API: Complete an unassigned task or assigned to another user

### ISSUE THREAD

**Issue by MernaMustafa** [camunda/camunda-platform#128]
I expect that I can complete only tasks that are assigned to me, not to another user, this worked fine in Camunda Cloud UI but when I use Tasklist REST API I can complete any task as long as I have the task Id 

![493f109c-10fd-4158-92a0-e47b8f03b29c](https://user-images.githubusercontent.com/42828113/235435039-7e2e1207-f814-466c-bdf5-9c2d6fa8284d.jpg)

![bd04cd0d-7aff-4da3-bb20-962f9b9c943e](https://user-images.githubusercontent.com/42828113/235435862-688398d4-4e43-4769-ad17-3475673a6ab3.jpg)

Also, I found out that I can complete an unassigned task

![e45e9c57-e70a-4bc7-b34c-8f6d33b9f39f](https://user-images.githubusercontent.com/42828113/235671683-0aa3bd08-ef88-4752-911e-0b05900e6c0d.jpg)

I think these cases should be handled with the following errors 

![2cd80570-10bc-448d-ba70-fb0e2f49c167](https://user-images.githubusercontent.com/42828113/235671859-18e078d0-2a32-4a82-8384-93201942a72c.jpg)

**Comment by ce-dmelnych** [comment]
Hello @MernaMustafa!
Thank you for raising this issue.

If you are using the [JWT authentication token](https://docs.camunda.io/docs/self-managed/tasklist-deployment/tasklist-authentication/#use-identity-jwt-token-to-access-tasklist-api), the behaviour you described is expected and was implemented intentionally. In this case, the API does not have a concept of a `user`, so it is up to the API consumer to manage `user`-related aspects.

By the way, the equivalent GraphQL [completeTask](https://docs.camunda.io/docs/apis-tools/tasklist-api/mutations/complete-task/) mutation operates in the same manner.

We acknowledge the need to improve our documentation to avoid confusion in the future. 
Thanks again for bringing this to our attention.

Best regards,
Dmytro.
