### ISSUE TITLE
Camunda SaaS: Creating groups 

### ISSUE THREAD

**Issue by MernaMustafa** [camunda/camunda-platform#129]
How can I create groups in Camunda Cloud? 
I found that there is Identity UI in self-managed, but I can't find something equivalent in SaaS 
![45e7bde8-cdbf-43b6-ad0e-108d885adaf7](https://user-images.githubusercontent.com/42828113/235674591-b20bac95-cf17-4b4b-8b20-810335138f3d.png)

**Comment by hisImminence** [comment]
Hi @MernaMustafa,

thanks for your question. 

> How can I create groups in Camunda Cloud?

This is not supported as of now. Instead you can directly assign roles to each member of the org and by that control their access.

You can have a look into our documentation if you want to know more details (see [manage users](https://docs.camunda.io/docs/components/console/manage-organization/manage-users/)).

I hope this answered all you questions? Feel free to reopen if you have a follow up!
