### ISSUE TITLE
Identity cannot connect to keycloak by running docker-compose.yaml

### ISSUE THREAD

**Issue by mircea-cm** [camunda/camunda-platform#20]
Hello,
By running the default docker-compose file
` docker-compose up -d` I see that Identity cannot connect to Keycloak. Also, the full stack is useless because Keycloak doesn't allow any HTTP endpoint, and connecting to Keycloak from the browser doesn't work.

I use this workaround to make it work.
1. wait for Keycloak to start
2. Set sslRequired to NONE by following these steps:
`docker exec -it keycloak bash`
`cd opt/jboss/keycloak/bin`
`./kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin`
`./kcadm.sh update realms/master -s sslRequired=NONE`
4. Connect to Keycloak on [http://localhost:18080/](http://localhost:18080/)
5. Go to Realm settings -> Login -> and set Require SSL to NONE
6. Save and wait for Identity to reconnect.

Regards,
Mircea C.

**Comment by dfulgham** [comment]
I haven't had this issue with the following compose file


other containers left out*
`
keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
    ports:
      - "18080:8080"
    networks:
      - camunda-platform

  identity:
    image: camunda/identity:8.0.0
    container_name: identity
    environment:
      SERVER_PORT: 8084
      KEYCLOAK_URL: http://keycloak:8080/auth
      IDENTITY_AUTH_PROVIDER_ISSUER_URL: http://<host-ip>:18080/auth/realms/camunda-platform
      IDENTITY_URL: http://<host-ip>:8084
      IDENTITY_AUTH_PROVIDER_BACKEND_URL: http://keycloak:8080/auth/realms/camunda-platform
      KEYCLOAK_INIT_OPERATE_SECRET: <secret>
      KEYCLOAK_INIT_OPERATE_ROOT_URL: http://<host-ip>:8081
      KEYCLOAK_INIT_TASKLIST_SECRET: <secret>
      KEYCLOAK_INIT_TASKLIST_ROOT_URL: http://<host-ip>:8082
      KEYCLOAK_INIT_OPTIMIZE_SECRET: <secret>
      KEYCLOAK_INIT_OPTIMIZE_ROOT_URL: http://<host-ip>:8083
      KEYCLOAK_USERS_0_USERNAME: "demo"
      KEYCLOAK_USERS_0_PASSWORD: "demo"
      KEYCLOAK_USERS_0_FIRST_NAME: "demo"
      KEYCLOAK_USERS_0_ROLES_0: "Identity"
      KEYCLOAK_USERS_0_ROLES_1: "Optimize"
      KEYCLOAK_USERS_0_ROLES_2: "Operate"
      KEYCLOAK_USERS_0_ROLES_3: "Tasklist"
    ports:
      - "8084:8084"
    networks:
      - camunda-platform
    depends_on:
      - keycloak

`

**Comment by jessesimpson36** [comment]
@mircea-cm , sorry this issue hasn't gotten a lot of attention since it was created.  when I run the docker-compose.yaml file, I can successfully authenticate and use the components.  I suspect that something has been fixed in the meantime without this ticket being updated. 

I'm going to close this issue, but please re-open it if you still have this problem.
