### ISSUE TITLE
Please provide ARM based images

### ISSUE THREAD

**Issue by akkie** [camunda/camunda-platform#21]
There was already an open issue in the camunda-cloud/camunda-cloud-get-started repository, which unfortunately was removed with the launch of Camunda Platform 8. But the issue still remains.

We need images for tasklist, operate and zeebe itself which are based on the ARM architecture. There are actually a lot of issues on Apple Silicon based machines which are based on the ARM processor architecture. The problems are that operate periodically isn't reachable and also Zeebe dies periodically.

**Comment by akkie** [comment]
As a workaround it's possible to build an image for Zeebe on an ARM based machine by checking out [Zeebe](https://github.com/camunda/zeebe) and running the following commands:

```
 mvn dependency:get -B \
    -DremoteRepositories="camunda-nexus::::https://app.camunda.com/nexus/content/repositories/public" \
    -DgroupId="io.camunda" -DartifactId="camunda-zeebe" \
    -Dversion="8.0.3" -Dpackaging="tar.gz" -Dtransitive=false

mvn dependency:copy -B \
    -Dartifact="io.camunda:camunda-zeebe:8.0.3:tar.gz" \
    -DoutputDirectory=./ \
    -Dmdep.stripVersion=true

docker build --no-cache --build-arg DISTBALL=camunda-zeebe.tar.gz -t zeebe:latest --target app .
```

But for operate and tasklist this is not possible because the repos are not available public.

**Comment by akkie** [comment]
OK, I found the Zeebe related issue: https://github.com/camunda/zeebe/issues/6155

But we still need images for tasklist and operate.

**Comment by Benjoyo** [comment]
Yes, very much needed. Doesn’t hurt to raise the pressure with another issue here 😉

**Comment by vlad-healthhelper** [comment]
I've been asking on Camunda forum since march. Looks like this is still an issue

**Comment by felix-mueller** [comment]
Thank you for raising it. We are aware of the issue and plan to work on it within the next months.

**Comment by namero999** [comment]
Hello, are there updates for the ARM images that can run on M1 hardware?

Operate and zeebe are still failing to run, with output

`zeebe The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by felix-mueller** [comment]
@megglos I believe with the latest alpha (alpha3) it should be working as expected right?

**Comment by aleksander-dytko** [comment]
Hi Everyone, the arm-64 docker images has been added to our release pipeline and now you can run camunda Platform 8 on M1/M2 CPU starting from 8.2 alpha3. 

Keycloak configuration for arm can be found in https://github.com/camunda/camunda-platform#running-on-arm64-based-hardware
