### ISSUE TITLE
Process History not showing user form variables

### ISSUE THREAD

**Issue by dfulgham** [camunda/camunda-platform#22]
For example

![image](https://user-images.githubusercontent.com/1512108/179085292-3fdeef13-ee0a-4f84-9f7d-39e3b48ade5e.png)

The user task "Mayor Decides: in the process has a form that has a number of variables... They should show when you click on the task.  Variables show fine for other service tasks, dmn's etc. but nothing for forms.

![image](https://user-images.githubusercontent.com/1512108/179086188-80c4d194-eada-486e-a000-7a17fc92cd78.png)

**Comment by jessesimpson36** [comment]
Hi @dfulgham ,

Thanks for letting us know about this bug, however, the proper place to be posting this is the [Camunda Forums](http://forum.camunda.io/). 

Re-open if you feel this issue is related to the docker-compose deployment method.

Thanks
