### ISSUE TITLE
docker-compose does not work

### ISSUE THREAD

**Issue by billbarni** [camunda/camunda-platform#24]
Does anyone just clones this repo and runs it?

Have anyone tested just cloning and running it?

I am confused how many commits are done to this repo and the connection to keycloak and elasticsearch between the images is not working. Nothing matches the documentation. Authentication cannot be executed...

**Comment by WarenaReveal** [comment]
I found docker compose works for me. What error are you getting?

**Comment by billbarni** [comment]
I have 4 friend developers. NONE of them can run this repo.
Tasklist 8.0.5 and 8.0.4 don't work.

Keycloak gets lost starting up and takes 10 minutes for NOT REASON and then none of the platforms can connect to it.

This repository is NOT WORKING.
