### ISSUE TITLE
Support older versions of docker and docker-compose

### ISSUE THREAD

**Issue by dennisfabri** [camunda/camunda-platform#26]
Linux distros (like Ubuntu) do not include your required version of docker into their current version. Therefore the docker-repo has to be used. This adds additional questions like licensing and support to just trying Camunda 8.

**Comment by jessesimpson36** [comment]
Hi @dennisfabri ,

Did starting the application  from a previous version of docker not work for you? I'm trying to understand if there is a bug that needs fixed, or if this is a clarification you want us to make inside our README.md file.  And if so, then I can start some of those discussions with people within Camunda.

I'm also not sure what licensing / support concerns you have, but you are permitted to run the software that we make publicly available. All software publicly available on github is free to try out.

We classify people who use our camunda-platform and camunda-platform-helm repo's on their own infrastructure under the category of "Self-Managed", and the pricing for that is listed here:
https://camunda.com/pricing/

**Comment by hisImminence** [comment]
Hey @dennisfabri, 

I will close this issue for now. Feel free to reopen if you have more to add!
