### ISSUE TITLE
Apple Silicon (arm64) Container keycloak Error

### ISSUE THREAD

**Issue by anderskristian** [camunda/camunda-platform#272]
Container keycloak  Error 
 ! keycloak The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 

Current version 19.0.3 does NOT support arm64
Latest version 22.0.1 supports arm64

Therefore change file .env
KEYCLOAK_SERVER_VERSION=22.0.1

 
 I have tested that I can upload a BPMN and run it.

**Comment by venkatajalapathy** [comment]
I do get the below error when trying to build the Docker image from the Dockerfile in .keycloak/Dockerfile https://github.com/camunda/camunda-platform/blob/main/.keycloak/Dockerfile.

Please help to suggest!

(microdnf:7): librhsm-WARNING **: 03:43:29.574: Found 0 entitlement certificates
Downloading metadata...

error: cannot update repo 'ubi-8-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/aarch64/baseos/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com]

**Comment by jessesimpson36** [comment]
Newest version supports Keycloak 22, which has ARM support.
