### ISSUE TITLE
docker-compose.yaml endless loop, docker-compose-core.yaml does not finish.

### ISSUE THREAD

**Issue by dark-passages** [camunda/camunda-platform#283]
# docker-compose.yaml

After the creation of 9 containers docker-compose keeps repeating the following messages on the screen:

> optimize       | 08:28:49.789 [ZeebeImportScheduler-1] WARN  o.c.o.s.i.z.f.AbstractZeebeRecordFetcher - No Zeebe index of type zeebe-record-process found to read records from!
> optimize       | 08:28:49.789 [ZeebeImportScheduler-1] INFO  o.c.o.s.i.z.m.ZeebeProcessDefinitionImportMediator - Records of type PROCESS from partition 1 imported in page: 0
> optimize       | 08:28:49.791 [ZeebeImportScheduler-1] WARN  o.c.o.s.i.z.f.AbstractZeebeRecordFetcher - No Zeebe index of type zeebe-record-process-instance found to read records from!
> optimize       | 08:28:49.791 [ZeebeImportScheduler-1] INFO  o.c.o.s.i.z.m.ZeebeProcessInstanceImportMediator - Records of type PROCESS_INSTANCE from partition 1 imported in page: 0
> optimize       | 08:28:49.791 [ZeebeImportScheduler-1] WARN  o.c.o.s.i.z.f.AbstractZeebeRecordFetcher - No Zeebe index of type zeebe-record-variable found to read records from!
> optimize       | 08:28:49.791 [ZeebeImportScheduler-1] INFO  o.c.o.s.i.z.m.ZeebeVariableImportMediator - Records of type VARIABLE from partition 1 imported in page: 0
> optimize       | 08:28:49.795 [ZeebeImportScheduler-1] WARN  o.c.o.s.i.z.f.AbstractZeebeRecordFetcher - No Zeebe index of type zeebe-record-incident found to read records from!
> optimize       | 08:28:49.795 [ZeebeImportScheduler-1] INFO  o.c.o.s.i.z.m.ZeebeIncidentImportMediator - Records of type INCIDENT from partition 1 imported in page: 0
> connectors     | 2023-08-17T08:28:53.356Z  WARN 1 --- [pool-2-thread-9] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.368Z  WARN 1 --- [pool-2-thread-1] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.368Z  WARN 1 --- [pool-2-thread-2] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.368Z  WARN 1 --- [pool-2-thread-5] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.384Z  WARN 1 --- [pool-2-thread-1] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.391Z  WARN 1 --- [pool-2-thread-3] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.392Z  WARN 1 --- [pool-2-thread-6] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.419Z  WARN 1 --- [pool-2-thread-8] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.419Z  WARN 1 --- [pool-2-thread-9] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.419Z  WARN 1 --- [pool-2-thread-4] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.419Z  WARN 1 --- [pool-2-thread-7] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.619Z  WARN 1 --- [pool-2-thread-2] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.619Z  WARN 1 --- [ool-2-thread-10] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.619Z  WARN 1 --- [pool-2-thread-5] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:28:53.729Z  WARN 1 --- [pool-2-thread-1] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.465Z  WARN 1 --- [pool-2-thread-3] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.477Z  WARN 1 --- [pool-2-thread-6] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.477Z  WARN 1 --- [pool-2-thread-9] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.477Z  WARN 1 --- [pool-2-thread-4] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.502Z  WARN 1 --- [pool-2-thread-6] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.502Z  WARN 1 --- [pool-2-thread-7] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.514Z  WARN 1 --- [pool-2-thread-2] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.531Z  WARN 1 --- [pool-2-thread-5] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.531Z  WARN 1 --- [ool-2-thread-10] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.531Z  WARN 1 --- [pool-2-thread-3] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.531Z  WARN 1 --- [pool-2-thread-1] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.746Z  WARN 1 --- [pool-2-thread-4] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.746Z  WARN 1 --- [pool-2-thread-9] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.747Z  WARN 1 --- [pool-2-thread-8] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.
> connectors     | 2023-08-17T08:29:03.863Z  WARN 1 --- [pool-2-thread-6] i.c.z.client.impl.ZeebeCallCredentials   : The request's security level does not guarantee that the credentials will be confidential.

When trying to access any of the given URL's
> Call Zeebe engine via localhost:26500
> Operate http://localhost:8081/
> Tasklist: http://localhost:8082/

They redirect to: 

> http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/auth?client_id=operate&redirect_uri=http%3A%2F%2F192.168.178.6%3A8081%2Fidentity-callback&response_type=code&scope=openid+email&state= 

but then nothing happens, even if I change localhost into the IP address of the container.

To me, it looks like the containers are up and running, but there is an error in the script with a loop.

# docker-compose-core.yaml

After the creation of 5 containers the screen shows:

> connectors     | 2023-08-17T09:00:34.280Z  INFO 1 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
> connectors     | 2023-08-17T09:00:34.281Z  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
> connectors     | 2023-08-17T09:00:34.282Z  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms

but then there is nothing. I can sign into the Operate and Tasklist websites this time. 
Was hoping to get my command prompt back.

**Comment by aabouzaid** [comment]
That issue comes from using older Docker Compose specs. In our case, we only support Docker Compose version 1.27.0+.

More details:
https://github.com/camunda/camunda-platform#using-docker-compose
