### ISSUE TITLE
FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by mb8z** [camunda/camunda-platform#31]
All containers seem to be running smooth, except for postgres – `FATAL:  role "root" does not exist`.
Have anyone already encountered this issue and know how to fix it?

**Comment by upgradingdave** [comment]
I also saw this today. 

I researched and I think this is related to the `pg_isready` command using `root` by default? Seems similar to this issue: https://github.com/peter-evans/docker-compose-healthcheck/issues/16

Updating [Line 156 in docker-compose.yaml](https://github.com/camunda/camunda-platform/blob/8dbf21ac73de6290cc3c6c80f1f2c5df30d55286/docker-compose.yaml#L156) seems to make it happier: 

```
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
```

**Comment by jessesimpson36** [comment]
I just started a new instance and found that the error `FATAL:  role "root" does not exist` ,  is not present. I also checked that line of the docker-compose.yaml file and found that the proposed change was already made. So I'm going to close this issue.  Re-open if I'm wrong in my assessment.
