### ISSUE TITLE
Missing root user in Zeebe container

### ISSUE THREAD

**Issue by michals96** [camunda/camunda-platform#314]
Hey guys, just a shower thought. Recently I've been trying to setup some custom security stuff in Zeebe that required me to do some root actions. It seems like the default Zeebe container that we get as part of the docker compose does not have a root user (or sudo for that matter) configured. It might be pretty useful. Thanks.

**Comment by jessesimpson36** [comment]
Zeebe being ran as a non-root user is a security feature.  to override it, you should be able to set `user: root` in docker-compose.yaml and it will run as root instead.

heres some evidence of it working:
```
> docker container ls | grep zeebe
2c12ab69f25f   camunda/zeebe:8.3.1                                              "tini -- /usr/local/…"   About a minute ago   Up 2 seconds (health: starting)   0.0.0.0:9600->9600/tcp, :::9600->9600/tcp, 0.0.0.0:26500->26500/tcp, :::26500->26500/tcp, 26501-26502/tcp   zeebe


> docker exec -it 2c12ab69f25f whoami
root
> 
```
