### ISSUE TITLE
Support monitoring in compose file

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform#319]
Customers would like basic monitoring of their docker compose deployments. 

There's a few points to consider:

- Given that the compose deployment method is not recommended for production, does adding this feature make it more likely that customers will use this compose deployment method in production ?
- It looks like a pretty easy addon and already implemented here: https://github.com/camunda/zeebe/tree/main/monitor

Related to: [SUPPORT-18148](https://jira.camunda.com/browse/SUPPORT-18148)

**Comment by jessesimpson36** [comment]
Notes from team meeting:
The Distribution team doesn't see much benefit for including the monitoring stack inside the docker compose deployment method.  As a workaround, existing customers can review https://github.com/camunda/zeebe/tree/main/monitor  and add their sections into their own docker-compose files.

I still want to leave this issue open in case more support tickets want to link against it.  That could be a sign that this topic needs to be escalated.

**Comment by theburi** [comment]
The monitoring page we provide https://github.com/camunda/zeebe/tree/main/monitor deploys the monitoring stack with Docker Compose, but it does not work. 
The Prometheus and Grafana configurations are not compatible with docker-compose deployment but are built for K8s. We should fix this example on a page and include a working configuration. It is a very reasonable use case for developers or SRE to work with Camunda and see how it behaves using Grafana. Even in dev environments, a monitoring stack could be useful.

**Comment by aabouzaid** [comment]
Since Docker Compose is not a production environment, there is no plan to add production monitoring components.
