### ISSUE TITLE
Docker compose file - to be updated to use UID 1000 as the default user for containers

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-platform#371]
This is to accommodate the change that the zeebe image runs with unprivileged user by default - https://github.com/camunda/camunda-docs/blob/main/docs/self-managed/operational-guides/update-guide/820-to-830.md#zeebe-docker-image-now-runs-with-unprivileged-user-by-default

The Helm charts implement this change already. The docker compose file is yet to implement this.

**Comment by aabouzaid** [comment]
The default user now is `1001`.

**Comment by jessesimpson36** [comment]
```
> docker exec -it zeebe sh

$ whoami
camunda

$ cat /etc/passwd
...
camunda:x:1001:1001::/usr/local/zeebe:/usr/sbin/nologin
```

docker compose will use unprivileged users because the images use unprivileged users.
