### ISSUE TITLE
Move MailHog to `docker-compose.yaml`

### ISSUE THREAD

**Issue by pihme** [camunda/camunda-platform#47]
Web Modeler Self Managed uses MailHog as a fake Email Server. It has a Web UI where you can see sent messages.

This functionality might also be interesting for KeyCloak, Optimize. Therefore MailHog could be moved into the base file.

**Comment by hisImminence** [comment]
Hey @pihme. 

We won't fix this for now. Feel free to reopen if you have more to add. Thanks!
