### ISSUE TITLE
Add short documentation on how to download connector templates

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform#53]
### Problem

Customers are already asking how to make Connector templates available in Web Modeler Self-Managed Beta:
- https://forum.camunda.io/t/camunda-8-connectors-bundle/40596
- https://forum.camunda.io/t/web-modeler-self-managed-beta/40545

### Solution

Add a paragraph here https://github.com/camunda/camunda-platform#connectors that describes that you need to download and import the templates yourself, where the templates are and how to import them.

**Comment by tmetzke** [comment]
I added an answer to the forum thread. But adding the same link and a description to the platform repository can definitely not hurt, I guess 👍
