### ISSUE TITLE
Web Modeler login information in README.md is not correct

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform#57]
The [Web Modeler](https://github.com/camunda/camunda-platform#web-modeler) section of the README.md states, in part:

> Now you can access Web Modeler Self-Managed and log in with the user `demo` and password `demo`

However, an email address is required for login, it should state:

> Now you can access Web Modeler Self-Managed and log in with the user `demo@acme.com` and password `demo`

**Comment by pihme** [comment]
Cannot reproduce with current code on main. (`76f1f2`)

Login allows me to use either username `demo` or email `demo@acme.com`.

![image](https://user-images.githubusercontent.com/14032870/203789274-24949fb1-d808-4968-a829-2b61c8be5f49.png)

**Comment by daniel-ewing** [comment]
I cannot find the issue in the web-modeler repo, but after I created this issue, I saw that a fix was made to web-modeler to use either username or email for login.  So this can be closed.
