### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by pihme** [camunda/camunda-platform#630]
This link is broken: https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/overview/

Appears in README at `We recommend using [SaaS](https://camunda.com/get-started/) or [Helm/Kubernetes](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/overview/) for development.`

**Comment by aabouzaid** [comment]
@pihme Thanks for reporting this and nice to see you again Peter :raised_hands: 
I've fixed the URLs :ok_hand:
