### ISSUE TITLE
Outdated Keycloak version

### ISSUE THREAD

**Issue by eprigorodov** [camunda/camunda-platform#681]
The variable `CAMUNDA_PLATFORM_VERSION` in the `.env` file is declared as 8.5.0. 

Camunda [release notes for 8.5.0](https://github.com/camunda/camunda-platform/releases/tag/8.5.0) mention Keycloak v23:

> * deps: Update dependency org.keycloak:keycloak-core to v23 [SECURITY] (main) (#17102)

The current `.env` configuration pulls `KEYCLOAK_SERVER_VERSION=21.1.2`.

That outdated version is known to be not working with some Microsoft EntraID provider configurations ([Keycloak issue 20695](https://github.com/keycloak/keycloak/issues/20695)). The bug is fixed in Keycloak v23.0.0.

Proposed fix: update Keycloak dependency to 23.0.7

**Comment by manya706** [comment]
hey! can this be assigned to me?

**Comment by jessesimpson36** [comment]
Yes please!  Thank you @manya706

**Comment by manya706** [comment]
Hey @jessesimpson36 ! the keycloak version in .env is currently  24.0.5 not 21.1.2 , so this has been fixed already i guess

**Comment by manya706** [comment]
Oh I got why it is happening, Renovate [bot] updated all the dependencies when i cloned the repo.  It has suggested updates for other dependencies as well.

**Comment by jessesimpson36** [comment]
Oh I see.  Thank you for investigating @manya706 . I will then close this issue.
