### ISSUE TITLE
Tasklist - Session expired on login

### ISSUE THREAD

**Issue by mhammoudoddo** [camunda/camunda-platform#7]
Hello,
I deployed a new camunda image to docker using the file [docker-compose-core.yaml](https://github.com/camunda/camunda-platform/blob/main/docker-compose-core. yaml).
When I try to login to camunda tasklist using default username and password, the login succeeds but when camunda tries to access /graphql url an error 403 appears (in browser console) and I return to the login page with the following message: Session expired
is it related to a missing configuration in the compose docker file?

Thank you

**Comment by menski** [comment]
Hi @mhammoudoddo,

I cannot reproduce this error. Can you provide any more details about your setup, environment, server logs or any other specific instructions how to reproduce?

**Comment by mhammoudoddo** [comment]
hello ,
Everything is ok now after running the docker compose again.
I will close the issue
Thanks
