### ISSUE TITLE
Connectors container does not load env_file connectors_secrets.txt

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-platform#707]
Secrets passed to connector_secrets.txt are not exposed as env vars in Connectors container, therefore these secrets are not found while evaluating {{secrets....}} expressions in connector configs.

**Comment by aabouzaid** [comment]
@McAlm Where is this file `connector_secrets.txt` coming from? We don't have it in the repo.

**Comment by aabouzaid** [comment]
OK the file is `connector-secrets.txt` and I close this issue as we didn't hear back about it.
