### ISSUE TITLE
 failed: FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by MajinBuuNe-Ahihi** [camunda/camunda-platform#71]
hi everyone, when I create a user on Postgres by command line :
createuser -P hoangvmanh 
after i confirmed the password it did not work and show an error: 
**createuser: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist**

how can I fix it?

**Comment by jessesimpson36** [comment]
@MajinBuuNe-Ahihi ,

I have reproduced the behavior that you described, however, I don't think this is a problem with the camunda-platform repo.

By default, the createuser command tries to connect using the user in the shell you've exec'd into.   I would suggest adding `-U bn_keycloak` which corresponds to the `POSTGRES_USER` environment variable we specify in the docker-compose.yaml file.  Here is a link to the [relevant config lines](https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml#L222-L224).

And here is some proof that it works on a freshly installed instance:
```
> docker compose exec -it postgres bash
bash-5.1# createuser -U bn_keycloak -P hoangvmanh
Enter password for new role: 
Enter it again: 
bash-5.1# createdb -U bn_keycloak hoangvmanh
bash-5.1# psql -U hoangvmanh
psql (14.5)
Type "help" for help.

hoangvmanh=> 
```

I hope this helps.
