### ISSUE TITLE
Unable to access Operate on remote host

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-platform#72]
Hi folks, 

It seems to be unable to access Operate on remote host when deployed with Keycloak ([docker-compose.yaml](https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml)).

**Steps to reproduce:**

1. Have a remote host to deploy. I use AWS EC2 `t3.xlarge` with RH5 linux.
2. Make sure remote host is reachable. I use public IP assigned to my host.
3. Make sure remote host has exposed ports. I use AWS security rules with expose ports `8080-8084, 18080, 26500`.
4. Make sure you have installed [docker](https://serverfault.com/a/852298), [docker-compose](https://docs.docker.com/compose/install/linux/), git.
5. Clone [`camunda-platform`](https://github.com/camunda/camunda-platform) at your remote host.
6. Deploy platform version with keycloak: `docker-compose -f docker-compose.yaml up`.
7. Once deployed, go to operate in your browser: `XXX.XXX.XXX.XXX:8081`.
8. See being redirected to `localhost`: `http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/auth?client_id=operate&redirect_uri=http%3A%2F%2F1XXX.XXX.XXX.XXX%3A8081%2Fidentity-callback&response_type=code&scope=openid+email&state=`

---

<img width="838" alt="Screenshot 2022-12-19 at 11 57 15" src="https://user-images.githubusercontent.com/108870003/208398741-8578f381-d86f-41e9-9320-c32a9b20d701.png">

**Comment by joleaf** [comment]
I have a similar problem. You can see, that your request was forwarded to localhost. Thus, what I did was to change some env variables in the config: e.g., `CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_URL` at multiple places in the `docker-compose.yml` file to the public IP of the remote server.
Now the request forwards me to the correct address (and not localhost). However, as it is not http**s** and not on the "secure" localhost environment, I get the message "We are sorry...HTTPS required". So, is there a way to enable https?

**Comment by anyidea** [comment]
same issue

**Comment by jessesimpson36** [comment]
This seems relevant to a PR I just merged:
https://github.com/camunda/camunda-platform/pull/126
