### ISSUE TITLE
Support Elasticsearch 8

### ISSUE THREAD

**Issue by chenglin321** [camunda/camunda-platform#83]
Description

Zeebe and Operate should work with Elasticsearch 8.x

**Comment by Zelldon** [comment]
@felix-mueller I moved this issue here (from Zeebe), since I think this is more a general topic maybe you can add some content regarding our plans to it.

**Comment by felix-mueller** [comment]
@chenglin321 thank you for raising. we are currently looking into how we can support elastic 7 and 8 using elastic compatibility mode. We aim to release with 8.2, but cannot confirm yet.

**Comment by jessesimpson36** [comment]
I'm not quite sure what the current state of this is, so I'll just do a quick test to see if  containers come up healthy and I can login if i set the elasticsearch version to 8.7.0.

**Comment by jessesimpson36** [comment]
Seems to work fine. Is there any known issues with switching the version to 8.7.0?   I was able to login, make a basic BPMN diagram, run it, enter a form in Tasklist, and see charts get generated in Optimize.  I tested that my very basic diagram was able to be ran in zeebe play too.

**Comment by aabouzaid** [comment]
I'm closing this since ES 8 is already supported.
https://github.com/camunda/camunda-platform/blob/1fe501c3212852ebad2b71d3fddd43eda93154a5/.env#L9
