### ISSUE TITLE
Zeebe is not up.

### ISSUE THREAD

**Issue by ssebastian05** [camunda/camunda-platform#9]
Hi,
I deployed camunda8 in a VM using docker-compose-core.yaml. But  I don't get any response while I'm trying to access  Zeebe: http://localhost:26500/. I'm able to reach Operate and Tasklist.

**Comment by menski** [comment]
Zeebe is not a HTTP application. Zeebe itself is a headless application with exposes a gRPC protocol. You can use `zbctl` from the [release](https://github.com/camunda/camunda-platform/releases/tag/8.0.0) to access Zeebe itself. 

To verify Zeebe is up and running locally you can run

```
zbctl status --insecure
```

which should give you an output similar to following if Zeebe is up and running

```
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 8.0.0
Brokers:
  Broker 0 - 172.27.0.3:26501
    Version: 8.0.0
    Partition 1 : Leader, Healthy
```

You can read more about `zbctl` and other clients in our [documentation](https://docs.camunda.io/docs/apis-clients/cli-client/). 


Feel free to reopen this issue in case this didn't solved your issue.
