### ISSUE TITLE
someone help me i got this error io.grpc.StatusRuntimeException!!!

### ISSUE THREAD

**Issue by haihm1** [camunda/camunda-platform#970]
i got the above error when deploying camunda 8 using docker, can someone help me? here is my code:
![Screenshot 2024-10-21 at 23 16 29](https://github.com/user-attachments/assets/bfc64707-5ebd-47b1-ac67-e65800a330a7)
![image](https://github.com/user-attachments/assets/0342aa0c-8360-402f-8d78-afdb56e823f9)
![image](https://github.com/user-attachments/assets/5fbfb66b-a3dd-4cd8-9ece-528d183d48e4)
![image](https://github.com/user-attachments/assets/55607f5d-f9a3-49ff-aa62-d15d276ff223)
![image](https://github.com/user-attachments/assets/a00f0ba3-a09d-45ab-8e25-5fde7eb92f16)
![image](https://github.com/user-attachments/assets/2548a1f0-ce27-444d-a2e9-f0c1dad42653)
thanks everyone <3

**Comment by haihm1** [comment]
this is error
![image](https://github.com/user-attachments/assets/7bd2a081-849e-4d8c-b6ea-8285f72ede35)

**Comment by jessesimpson36** [comment]
@haihm1 we need more info on how you deployed this.  You said that you were running with docker,   were you using the compose file found in the camunda-platform repo, or is there a `docker run` command you used that you could share?

**Comment by aabouzaid** [comment]
I'm closing this issue since we didn't get any updates so far.
Feel free to provide the requested information.
